version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nestjs
      POSTGRES_DB: nesjsdb
    ports:
      - '5432:5432'
    volumes:
      - nestjs-postgres:/var/lib/postgresql/data # Tạo volume để lưu dữ liệu của PostgreSQL

  redis:
    container_name: nestjs-redis
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - nestjs-redis:/data # Tạo volume để lưu dữ liệu của Redis

  mongodb:
    container_name: nestjs-mongodb
    image: mongo:7.0.2
    restart: always
    ports:
      - '${MONGO_FORWARD_PORT:-27017}:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - nestjs-mongodb:/data/db

volumes:
  nestjs-postgres: # Volume cho PostgreSQL
  nestjs-redis: # Volume cho Redis
  nestjs-mongodb: # Volume cho MongoDB
