version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nestjs
      POSTGRES_DB: nesjsdb
    ports:
      - '5432:5432'
    volumes:
      - db-postgres:/var/lib/postgresql/data # Tạo volume để lưu dữ liệu của PostgreSQL

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - db-redis:/data # Tạo volume để lưu dữ liệu của Redis

volumes:
  db-postgres: # Volume cho PostgreSQL
  db-redis: # Volume cho Redis
